### ISSUE TITLE
Seeking Clarifications - M:1 Relationships & Raw

### ISSUE THREAD

**Issue by prashanth1k** [SouthRibbleTech/lucidql#2]
Great work on LucidQL. I am trying it out in a recent project and had a couple of questions. My apologies if I am seeking answers here. Hopefully, it helps others as well.

1. How should LucidQL behave in 1:1 and M:1 relationships?
My use case - I tend to fetch the user details with the account to display owner login/name, etc. in the account page.

Account model -
```
users() {
    return this.hasOne("App/Models/User", "primary_user_id", "id");
  }
```

'users' is null if I use the below query -
```
{
 "baseTable": "Account",
 "query": {
   "fields": [ "id" ],
   with": [
     {	"table": "users" }
   ]
 }
}
```
The results are the same if I use 'belongsTo' instead.

2. Is there any way of using 'raw'? 
(was it ignored because they can cause security issues?)

**Comment by SouthRibbleTech** [comment]
Thanks for the feedback.

I have not integrated raw because the control of which models can be used are set in the controller, so your right it would be a security issue.

As far as how "with" works, lucidql simply runs the underlying lucid library so it should be identical to that described in the docs.
